name: Devcontainer Image Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: ["Dockerfile"]
  pull_request:
    branches: [ "main" ]
    paths: ["Dockerfile"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2.1.0

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: devcontainer-base
        tags: |
          type=sha,format=long,value=${GITHUB_SHA}

    - name: Sign in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ghcr.io

    - name: Build and push Docker image
      id: container_build_and_push
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: ghcr.io/${{ github.repository }}:latest, ghcr.io/${{ github.repository }}:${{ steps.meta.outputs['type=sha'] }}
        push: true

    # - name: Publish Container Image as a Status
    #   id: container_image_status
    #   uses: octodemo/github-status-action@v3
    #   with:
    #     authToken: ${{ secrets.GITHUB_TOKEN }}
    #     state: success
    #     context: Container Image Published - ${{ inputs.container_type }}
    #     description: ${{ fromJSON(steps.container_build_and_push.outputs.metadata)['image.name'] }}
